# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "calixto-ti"
BBFILE_PATTERN_calixto-ti = "^${LAYERDIR}/"
BBFILE_PRIORITY_calixto-ti = "13"

LAYERDEPENDS_calixto-ti = "core"
LAYERSERIES_COMPAT_calixto-ti = "scarthgap"
